name: actionlint

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  actionlint:
    uses: ./.github/workflows/reusable-actionlint.yml
    with:
      validate_composite_actions: true
